 export enum STATUS {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

export enum CHAT_SESSION_STATUS {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    ENDED = "ENDED",
}

export enum CHAT_MESSAGE_SENDER_TYPE {
    BOT = "BOT",
    USER = "USER",
    AI_AGENT = "AI_AGENT",
}

export enum CHAT_MESSAGE_TYPE {
    TEXT_ONLY = "TEXT_ONLY",
    IMAGE_ONLY = "IMAGE_ONLY",
    PRODUCT = "PRODUCT",
    BOTTON = "BOTTON",
    QUICK_REPLY = "QUICK_REPLY",
    RANDOM = "RANDOM",
}

export enum INTERVENTION_ACTIVITY_STATUS {
    ACCEPETED = "ACCEPETED",
    PRESENTED = "PRESENTED",
    IGNORED = "IGNORED",
    REJECTED = "REJECTED",
}

export enum FISHOOK_INTENTS {
  ABANDONED_CART = "ABANDONED_CART",
  WINDOW_SHOPPER = "WINDOW_SHOPPER",

  JUST_BROWSING = "JUST_BROWSING",
  LIKE_AN_ITEM_NO_MONEY = "LIKE_AN_ITEM_NO_MONEY",
  TOO_EXPENSIVE = "TOO_EXPENSIVE",
  COULD_NOT_FIND_ITEM = "COULD_NOT_FIND_ITEM",

  BUY_NOW_PAY_LATER = "BUY_NOW_PAY_LATER",
  PAY_IN_BITS = "PAY_IN_BITS",
  NOTIFY_ME_MONTH_END = "NOTIFY_ME_MONTH_END",
}